package com.openclassrooms.p7.go4lunch.model;

public enum SortMethod {
    INTERESTED_ASCENDING,
    INTERESTED_DESCENDING,
    RATING_ASCENDING,
    RATING_DESCENDING,
    DISTANCE_ASCENDING,
    DISTANCE_DESCENDING,
    FAVORITE_ASCENDING,
    FAVORITE_DESCENDING,
    SEARCHED_ASCENDING,
    SEARCHED_DESCENDING,
    NONE
}
